# This is another way to do it, not necessary for the EC2 challenge project
#This helps you connect to AWS directly from GitHub
name: Terraform Deployment with Github Actions
on: [push]
jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: AWS authentication
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: git clone of my repo
        uses: actions/checkout@v3
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Init Project
        run: terraform init
      
      - name: Run TF plan
        run: terraform plan
      
      - name: Apply infrastructure
        run: terraform apply -auto-approve

